### ISSUE TITLE
Fix RFME querying/data writing so it doesn't error out

### ISSUE THREAD

**Issue by kfettich** [Diegod96/CFP-PAWS-Salesforce#3]
**Reference**: See email with subject "Fwd: An error occurred with your "RFME Analysis Flow" flow" from 10/8/2024

> An Error Occurred with Your "RFME Analysis Flow" Flow
You’ve received this email because an error occurred while your "RFME Analysis Flow" flow was running.
Error element Perform_Contact_RFM_Analysis (FlowActionCall).
An Apex error occurred: System.LimitException: Apex heap size too large: 238931302

**Comment by Diegod96** [comment]
Converted the Flow implementation into Apex Code to handle the massive amount of contact/opportunity records we are encountering
